#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_N]
#set_property PACKAGE_PIN A8         [get_ports {reset_n}]
#set_property IOSTANDARD LVCMOS18    [get_ports {reset_n}]

set_property PACKAGE_PIN F7         [get_ports {lcd_d[0]}]
set_property PACKAGE_PIN F8         [get_ports {lcd_d[1]}]
set_property PACKAGE_PIN D6         [get_ports {lcd_d[2]}]
set_property PACKAGE_PIN D7         [get_ports {lcd_d[3]}]
set_property PACKAGE_PIN E5         [get_ports {lcd_rs}]
set_property PACKAGE_PIN E6         [get_ports {lcd_rw}]
set_property PACKAGE_PIN F6         [get_ports {lcd_e}]

set_property IOSTANDARD LVCMOS18    [get_ports {lcd_d[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_d[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_d[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_d[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_rs}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_rw}]
set_property IOSTANDARD LVCMOS18    [get_ports {lcd_e}]
